"""E3 — the national-baseline handover pack.

This Indiana app is the BASELINE for a national tool. What transfers is not the Indiana data; it
is the contracts, the grammar, and — most valuable — the specific errors this build made, because
a national build will make every one of them at 50x the scale.

GENERATED, not hand-typed, so it cannot drift from the estate it describes.
"""
import os, json, datetime
from google.cloud import bigquery

REPO = r"C:\Users\ahend\Downloads\Decennial Summer Work\Project Reverse Uno\California\ca-capacity-deploy\indiana-application-decennial"
DS, EN = "energy-platfrom.indiana_app", "energy-platfrom.energy"
client = bigquery.Client(project="energy-platfrom")


def rows(sql): return [dict(r) for r in client.query(sql)]


def q1(sql): return list(client.query(sql))[0]


reg = rows(f"""SELECT table_name, ANY_VALUE(n_rows) n_rows, ANY_VALUE(source) source,
  ANY_VALUE(method) method, MAX(built_at) built_at FROM `{DS}._registry`
  GROUP BY table_name ORDER BY table_name""")
eps = rows(f"""SELECT source_name, status, endpoint, endpoint_kind, acquisition_method
  FROM `{EN}.registry_sources` WHERE updated_by LIKE 'indiana-app%' ORDER BY (status='blocked'), source_name""")
flag = q1(f"""SELECT COUNTIF(has_si_signal) f, COUNTIF(has_si_signal AND fits_min_bess_5mw) b,
  COUNTIF(has_si_signal AND fits_dc_25mw) d FROM `{DS}.in_si_sites_flags_v2`""")
cov = rows(f"""SELECT signal, parcels_admitted, parcels_reached FROM `{DS}.in_si_signal_coverage`
  WHERE parcels_admitted > 0 ORDER BY parcels_admitted DESC""")

o = [f"# NATIONAL HANDOVER PACK — generated {datetime.date.today()}", "",
     "**GENERATED by `scripts/build_handover_pack.py`.** Regenerate; never hand-edit.", "",
     "This Indiana app is the baseline for a national tool. **What transfers is not the data —",
     "it is the contracts, the honesty grammar, and the errors.** A national build will make every",
     "mistake below at fifty times the scale, so the errors are listed first.", "",
     "---", "", "## 1. The errors that cost the most, and what each one teaches", "",
     "| the reading | the truth | the transferable rule |", "|---|---|---|",
     "| `has_si_signal` = 847,410 parcels | 99.2% was empty land; the only parcel-keyed input was footprint ABSENCE | a signal that fires on almost everything is measuring the wrong thing |",
     "| 0 of 945,896 signal rows joined to parcels | three key NAMESPACES (`IN:` prefix, 7-digit local id, punctuated state id) | when a join reads zero, suspect the key format before the data |",
     "| \"Marion has no crosswalk\" | true of the tables we HELD; the county publishes one (`sde_Parcel/5`, 347,049 rows) | a dead end in your warehouse is not a dead end in the publisher's catalogue |",
     "| 14,293 parcels admitted | 95% of South Bend \"code enforcement\" is litter and weeds; 90% of Evansville \"demolition\" is residential teardowns | read the VALUE VOCABULARY before trusting a count |",
     "| 92 data-centre pins | census CITY CENTROIDS rendered as facility locations | a centroid answers \"which town\", never \"how far\" |",
     "| 100% spatial match on first run | one inverted whole-Earth parcel swallowed every point | a perfect join is a defect until proven otherwise |",
     "| \"0 high-priority violators\" | 95 exist; `distress_class` is a priority ladder that counts each facility once | never read a category off a mutually-exclusive ladder |",
     "| 95 rates below the wholesale floor | most were 0.0, an ABSENT rate treated as zero | unpublished is NULL, never 0 — and check your own code against that rule |",
     "| a 12-month LMP average | the feed had a gap; it was 39 days of summer | assert the window you got, not the one you asked for |",
     "| \"9 ECHO columns missing\" | all present under SCREAMING_SNAKE vs camelCase | exact-name matching across naming conventions produces false gaps |",
     "| WARN deduped to 1,252 | a symmetric 74/74 split was city WHITESPACE, not divergence | suspiciously symmetric residuals are usually formatting |",
     "| 199 of 199 objects wired | the denominator moves on every build that registers something | make the census a script, never a number in a document |",
     "", "## 2. The rulings that shaped the product", "",
     "1. **Seller intent is admitted at the NON-RESIDENTIAL level only.** A ~300 MW datacentre and",
     "   a ~5 MW BESS both need land a house does not have.",
     "2. **Severity gates every signal.** Only distress that would plausibly move an owner to sell.",
     "3. **Capability is a separate question from signal.** 69% of flagged parcels cannot host even",
     "   5 MW — an expected and useful filter, not a defect. Measure it beside the flag.",
     "4. **Where two measures disagree, take the SMALLER** and label it disputed. The larger number",
     "   is the one that makes a site look viable.",
     "5. **Vacancy is two things.** Footprint absence is a land state, not intent.",
     "6. **Union-and-dedupe every duplicated subject**; never two partial layers of one thing.",
     "7. **Cannot-assess renders as itself** and is dropped from the denominator, never scored 0.", "",
     "## 3. The payload contract", "",
     "```", "BigQuery (indiana_app) --> gzipped GeoJSON/JSON --> committed --> browser DecompressionStream",
     "```", "",
     "- one county file per FIPS; the class union is exported from ONE snapshot so two counties are",
     "  never two generations (the partial-swap hazard)",
     "- an export ABORTS rather than half-writes if its source columns are absent",
     "- detail fields are emitted only where they mean something; an absent key reads as \"no",
     "  admitted signal\", which is the truth, not as \"cannot assess\"",
     "- every figure carries its source table and build date, read from `_registry` at render time", "",
     f"## 4. The estate as handed over ({len(reg)} registered objects)", "",
     f"| | |", "|---|---:|",
     f"| registered objects | {len(reg)} |",
     f"| parcels flagged with an admitted seller-intent signal | {flag.f:,} |",
     f"| …that can host ≥5 MW BESS | {flag.b:,} |",
     f"| …that can host ≥25 MW datacentre | {flag.d:,} |",
     f"| signals reaching a parcel | {len(cov)} |",
     f"| endpoints recorded | {len(eps)} ({sum(1 for e in eps if e['status']=='blocked')} BLOCKED with the wall verbatim) |",
     "", "## 5. What a national build must acquire that Indiana did not have", "",
     "- **Owner names on parcels.** `mat_parcel_attrs.parcel_owner` is NULL on all 3,553,381 Indiana",
     "  rows. That single gap blocks FIVE signals (D9, D18, D11, D27, and IDEM enforcement).",
     "- **Component-level tariffs.** Indiana has 3 component rows and 2 are `not_held`. No",
     "  component-level Indiana tariff exists in the estate, so no rate can be quoted — only",
     "  compared against four proxies with a wholesale floor.",
     "- **Local ordinance text at scale.** Codified search finds almost nothing: the",
     "  decision-relevant regulation is county MORATORIA on county websites, and one county",
     "  approved a 7.1M sq ft datacentre by administrative interpretation under a code that never",
     "  mentions data centres. **Codified silence is not permissiveness.**",
     "", "## 6. Signals that reach a parcel today", "",
     "| signal | parcels reached | admitted |", "|---|---:|---:|"]
for c in cov:
    o.append(f"| `{c['signal']}` | {c['parcels_reached']:,} | {c['parcels_admitted']:,} |")

o += ["", "## 7. Blocked sources — do not retry without new terms", "", "| source | wall |", "|---|---|"]
for e in eps:
    if e["status"] == "blocked":
        o.append(f"| {str(e['source_name'])[:44]} | {str(e['acquisition_method'])[:120]} |")
o += ["", "Plus two standing permission questions for the operator: American Legal Publishing "
      "(robots grants `*`, terms forbid robots — a licence unlocks 17 counties), and whether a "
      "machine-readable `Allow` or prose terms govern, given 30+ hosts disallow `ClaudeBot` by "
      "name while serving the public freely.", ""]

open(os.path.join(REPO, "docs", "NATIONAL_HANDOVER.md"), "w", encoding="utf-8").write("\n".join(o) + "\n")
print(f"docs/NATIONAL_HANDOVER.md — {len(reg)} objects, {len(cov)} signals, {len(eps)} endpoints "
      f"({sum(1 for e in eps if e['status']=='blocked')} blocked)")
