"""Generate docs/CODE_CATALOG.md — every script, endpoint and loader we have written.

Written because the conversation that produced them will not be available again. GENERATED, not
hand-typed, so a future session can regenerate it after adding scripts rather than trusting a
list that has silently drifted.

Three sources, all mechanical:
  · the filesystem — every .py under scripts/ and scrapers/, with its docstring summary
  · `indiana_app._registry` — which tables/views each build produced
  · `energy.registry_sources` — endpoint URL, endpoint_kind and the literal re-scrape command,
    for rows this workstream appended
"""
import os, re, ast, datetime
from google.cloud import bigquery

REPO = r"C:\Users\ahend\Downloads\Decennial Summer Work\Project Reverse Uno\California\ca-capacity-deploy\indiana-application-decennial"
DS = "energy-platfrom.indiana_app"
EN = "energy-platfrom.energy"
client = bigquery.Client(project="energy-platfrom")

def summary_of(path):
    """First meaningful line of the module docstring — what the script is FOR."""
    try:
        src = open(path, encoding="utf-8", errors="ignore").read()
        doc = ast.get_docstring(ast.parse(src)) or ""
    except Exception:
        return "(unparseable)", []
    first = next((l.strip() for l in doc.splitlines() if l.strip()), "(no docstring)")
    urls = sorted(set(re.findall(r"https?://[A-Za-z0-9._~:/?#@!$&()*+,;=%<>-]+", src)))
    urls = [u.rstrip('",\').') for u in urls if "schemas.google" not in u]
    return first, urls

out = [f"# CODE CATALOG — generated {datetime.date.today()}", "",
       "Every script, endpoint and loader written for this application. **Generated by**",
       "`scripts/build_code_catalog.py` — regenerate it rather than editing by hand, so it cannot",
       "drift from what is actually on disk.", "",
       "Run everything from the repo root with the platform venv:", "", "```bash",
       'cd "C:\\Users\\ahend\\Downloads\\Decennial Summer Work\\Remaking Orennia\\energy-platform"',
       '$env:GOOGLE_APPLICATION_CREDENTIALS="C:\\Users\\ahend\\bq-key.json"',
       '$env:PYTHONIOENCODING="utf-8"',
       ".venv\\Scripts\\python.exe <path-to-script>", "```", ""]

# ---- 1. the scripts ----------------------------------------------------------------------
for folder, title in [("scripts", "Build & export scripts (`scripts/`)"),
                      ("scrapers", "Acquisition scripts (`scrapers/`)")]:
    root = os.path.join(REPO, folder)
    if not os.path.isdir(root): continue
    out += [f"## {title}", ""]
    rows = []
    for dirpath, _, files in os.walk(root):
        if "__pycache__" in dirpath or "_scratch" in dirpath or "_cache" in dirpath: continue
        for fn in sorted(files):
            if not fn.endswith(".py"): continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, REPO).replace("\\", "/")
            s, urls = summary_of(full)
            rows.append((rel, s, urls))
    out += ["| script | what it does | endpoints it touches |", "|---|---|---|"]
    for rel, s, urls in rows:
        eps = "<br>".join(f"`{u[:70]}`" for u in urls[:3]) if urls else "—"
        if len(urls) > 3: eps += f"<br>_…{len(urls)-3} more_"
        out.append(f"| `{rel}` | {s[:110]} | {eps} |")
    out += ["", f"_{len(rows)} scripts._", ""]

# ---- 2. what each build produced ----------------------------------------------------------
reg = [dict(r) for r in client.query(f"""
  SELECT table_name, source, method, n_rows FROM (
    SELECT table_name, ANY_VALUE(source) source, ANY_VALUE(method) method,
           ANY_VALUE(n_rows) n_rows, MAX(built_at) b
    FROM `{DS}._registry` GROUP BY table_name)
  ORDER BY table_name""")]
out += ["## Tables & views this workstream builds", "",
        f"{len(reg)} objects registered in `indiana_app._registry`. `source` names the input,",
        "`method` names the transformation — both are what a future session needs to rebuild.", "",
        "| object | rows | built from | method |", "|---|---:|---|---|"]
for r in reg:
    out.append(f"| `{r['table_name']}` | {r['n_rows'] if r['n_rows'] is not None else '—'} | "
               f"{str(r['source'])[:52]} | {str(r['method'])[:78]} |")
out.append("")

# ---- 3. endpoints, with type and the command that re-runs them ----------------------------
eps = [dict(r) for r in client.query(f"""
  SELECT source_name, status, endpoint, endpoint_kind, acquisition_method,
         ARRAY_TO_STRING(object_names, ', ') objs
  FROM `{EN}.registry_sources`
  WHERE updated_by LIKE 'indiana-app-session-%'
  ORDER BY (status='blocked'), source_name""")]
out += ["## Endpoints — URL, type, and the command that re-runs each", "",
        "From `energy.registry_sources`, rows appended by this workstream. The",
        "`indiana-app-session-20260815-endpoints` pass replaced prose endpoints (\"Evansville open",
        "data\", \"Messenger native CSV\") with the real addresses read out of the scrapers, and added",
        "the `endpoint_kind` and re-run command that were missing on all 31 original rows.", "",
        "| source | status | kind | endpoint | re-run |", "|---|---|---|---|---|"]
for e in eps:
    out.append(f"| {str(e['source_name'])[:44]} | {e['status']} | `{e['endpoint_kind'] or '—'}` | "
               f"`{str(e['endpoint'] or '—')[:62]}` | `{str(e['acquisition_method'] or '—')[:64]}` |")
out += ["", f"_{len(eps)} endpoint rows; "
        f"{sum(1 for e in eps if e['status'] == 'blocked')} BLOCKED with their wall recorded._", ""]

# ---- 4. the walls, verbatim ---------------------------------------------------------------
out += ["## BLOCKED sources — do not retry without new terms", "",
        "| source | wall |", "|---|---|"]
for e in eps:
    if e["status"] == "blocked":
        out.append(f"| {str(e['source_name'])[:44]} | {str(e['acquisition_method'] or '')[:100]} |")
out += ["", "Plus, from Lane F discovery (`scrapers/lane_f/`):",
        "- **D10 state tax warrants** — OJA INcite $600/yr individual, $5,000/yr business; Doxpop",
        "  resale from $38/mo. Procurement decision, not a scrape.",
        "- **D15 mechanics liens** — Doxpop / Fidlar Tapestry ($8.75 per search) / Laredo. No open",
        "  data presence in any of the 92 counties.",
        "- **A1 listings** — `properties.zoomprospector.com` robots.txt reads",
        "  `User-agent: * Disallow: /`. Lawful route is a data request to IEDC.",
        "- **Fidlar Direct Search** — free and does index FEDERAL TAX LIEN doc types, but is",
        "  reCAPTCHA-gated with an explicit anti-data-mining notice. Manual per-parcel use only.", ""]

open(f"{REPO}\\docs\\CODE_CATALOG.md", "w", encoding="utf-8").write("\n".join(out) + "\n")
print(f"docs/CODE_CATALOG.md — {len(reg)} registered objects, {len(eps)} endpoint rows")
