"""GENERATE docs/SI_SIGNALS.md — the whole SI signal system, measured rather than remembered.

Operator, 2026-08-22: *"we did a lot of SI signal work (through rescraping and adding new fields),
and I want to make sure all of the work is documented, including any next steps that may be in
order."*

⛔ WHY THIS IS GENERATED AND NOT WRITTEN. The account of the SI signals was spread across sixteen
backlog rows, three handoffs and a dozen script docstrings, and the one file that DID summarise it
— `docs/SIGNAL_REALITY.json` — went **five days without regenerating** while sitting on the
required reading list, still reporting `D19_warn` at 2 parcels. A hand-written summary of a system
this size is a snapshot that starts decaying the moment it is saved.

⭐ SO EVERY NUMBER BELOW IS A LIVE QUERY. The only hand-written parts are the NEXT STEPS at the
bottom, which are judgements and are labelled as such.

RE-SCRAPE COMMAND: python scripts/build_si_signals_doc.py
⛔ READ-ONLY against the warehouse; writes one markdown file.
"""
import io
import os
import sys
from datetime import datetime, timezone

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from google.cloud import bigquery

from si_upstream_sources import REPAIRS, SOURCES, YEAR_GAPS

DS = "energy-platfrom.indiana_app"
EN = "energy-platfrom.energy"
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "docs", "SI_SIGNALS.md")
client = bigquery.Client(project="energy-platfrom")

# ⚠ HAND-WRITTEN, AND LABELLED AS SUCH: what each widened clip is FOR. Everything else is queried.
WHY = {s[3]: s[4] for s in SOURCES}
WHY.update({t: w for t, _, _, w in REPAIRS})
WHY.update({t: w for t, _, _, w in YEAR_GAPS})


def q(sql):
    return list(client.query(sql).result())


print("measuring the signal system …", flush=True)
cov = q(f"""SELECT signal, corpus_rows, parcels_reached, parcels_admitted, parcels_ci,
                   first_event, last_event, corpus_keying
            FROM `{DS}.in_si_signal_coverage` ORDER BY parcels_admitted DESC, signal""")
intent = q(f"""SELECT signal, COUNT(DISTINCT parcel_key) parcels, COUNT(*) events,
                      ANY_VALUE(so_what) so_what
               FROM `{DS}.in_si_intent_signals` GROUP BY 1 ORDER BY parcels DESC""")
flags = q(f"""SELECT COUNTIF(has_si_signal) flagged,
                     COUNTIF(has_intent_signal) intent_parcels,
                     COUNTIF(has_si_signal AND si_last_event_date IS NULL
                             AND si_next_event_date IS NULL) undated,
                     COUNTIF(has_si_signal AND si_last_event_date IS NULL
                             AND si_next_event_date IS NULL
                             AND (si_first_event_date IS NOT NULL OR si_events_dated > 0)) still_false,
                     COUNTIF(si_next_event_date IS NOT NULL) scheduled
              FROM `{DS}.in_si_sites_flags_v2`""")[0]

print("measuring the upstream clips …", flush=True)
clips = []
for target in list(WHY):
    try:
        tb = client.get_table(f"{DS}.{target}")
    except Exception:
        continue
    clips.append((target, tb.num_rows, len(tb.schema)))
clips.sort(key=lambda r: -r[1])

# which clips actually feed something a reader sees?
spine = io.open(os.path.join(REPO, "scripts", "build_si_signal_v2.py"), encoding="utf-8").read()
cmbs = io.open(os.path.join(REPO, "scripts", "build_si_cmbs_signals.py"), encoding="utf-8").read()
intent_src = io.open(os.path.join(REPO, "scripts", "build_si_intent_signals.py"),
                     encoding="utf-8").read()
downstream = spine + cmbs + intent_src

L = []
w = L.append
w("# SI SIGNALS — the whole system, measured")
w("")
w("<!-- GENERATED by scripts/build_si_signals_doc.py. ⛔ DO NOT HAND-EDIT — edit the generator.")
w("     Every figure is a live query. The NEXT STEPS section is judgement and says so. -->")
w("")
w(f"> Generated {datetime.now(timezone.utc):%Y-%m-%d %H:%M} UTC. ⛔ **Nothing here is hand-typed "
  f"except the \"what it buys\" column and the next steps.**")
w("")
w("⛔ **WHY THIS FILE IS GENERATED.** The account of the SI signals lived across sixteen backlog "
  "rows, three handoffs and a dozen docstrings — and the one file that summarised it, "
  "`docs/SIGNAL_REALITY.json`, went **five days without regenerating** while on the required "
  "reading list, still reporting `D19_warn` at 2 parcels. A hand-written summary of a system this "
  "size decays from the moment it is saved.")
w("")
w("---")
w("")
w("## 1. THE HEADLINE")
w("")
w("| | |")
w("|---|---:|")
w(f"| parcels carrying a DISTRESS signal | **{flags.flagged:,}** |")
w(f"| parcels carrying a DECLARED-INTENT signal | **{flags.intent_parcels:,}** |")
w(f"| parcels with a SCHEDULED future event | **{flags.scheduled:,}** |")
w(f"| parcels the UI reports as undated | {flags.undated:,} |")
w(f"| …of those, how many we actually hold a date for | **{flags.still_false}** |")
w("")
w("⭐ **That last row is G145.** Before the fix, 8,573 parcels printed *\"date unknown\"* over a "
  "date we held, because the rollup read the last event **on or before today** and a scheduled tax "
  "auction is in the future. The honest residue is now the row above it, and every one of those "
  "says *\"the publisher does not date this record\"* rather than blaming our records.")
w("")
w("---")
w("")
w("## 2. EVERY DISTRESS SIGNAL — held → reached → admitted")
w("")
w("⚠ **A large drop is not a defect if it is stated.** We filter deliberately: C&I only, severity "
  "gates, 3+ violations. `scripts/audit_signal_display.py` fails only where a signal places far "
  "below what we hold **with no recorded reason**, and it currently reports zero.")
w("")
w("| signal | held | reached | admitted | C/I | date range |")
w("|---|---:|---:|---:|---:|---|")
for r in cov:
    rng = (f"{r.first_event} → {r.last_event}" if (r.first_event or r.last_event)
           else "the publisher dates none of these")
    held = f"{r.corpus_rows:,}" if r.corpus_rows is not None else "—"
    w(f"| `{r.signal}` | {held} | {r.parcels_reached:,} | **{r.parcels_admitted:,}** "
      f"| {r.parcels_ci:,} | {rng} |")
w("")
w("## 3. THE DECLARED-INTENT FAMILY — willingness STATED, not inferred")
w("")
w("⭐ Every D-code above INFERS willingness from distress. These REVEAL it, so they are counted "
  "separately and never folded into the flagged count.")
w("")
w("| signal | parcels | events | what it means |")
w("|---|---:|---:|---|")
for r in intent:
    w(f"| `{r.signal}` | **{r.parcels:,}** | {r.events:,} | {(r.so_what or '').strip()} |")
w("")
w("---")
w("")
w("## 4. THE FULL-WIDTH UPSTREAM CLIPS (G152)")
w("")
w("⛔ **THE PROBLEM THEY SOLVE.** `energy.si_signals` is **97,240,585 rows normalised to 13 "
  "columns**. Our clip of it was complete — 13 of 13 — so a column audit passed **on a reduction**. "
  "Everything the 19 upstream sources carry beyond those 13 was discarded before it reached us.")
w("")
w("⭐ **Operator ruling, 2026-08-21:** *\"Even if a source scrapes everything but one column, we "
  "still want to rescrape it for everything because that one field may contain something "
  "materially important.\"* So every source is clipped at FULL WIDTH with `SELECT *`, and the "
  "column count is asserted equal to the parent's at build time.")
w("")
w("| clip | rows | cols | feeds a signal? | what it buys |")
w("|---|---:|---:|:--:|---|")
for target, rows, cols in clips:
    feeds = "⭐ yes" if target in downstream else "not yet"
    why = WHY.get(target, "").replace("\n", " ").strip()
    if len(why) > 300:
        why = why[:297] + "…"
    w(f"| `{target}` | {rows:,} | {cols} | {feeds} | {why} |")
w("")
w(f"**{len(clips)} clips · {sum(r for _, r, _ in clips):,} Indiana rows held at full width.** "
  f"Guarded by `scripts/audit_si_upstream_width.py`, which is a checkpoint check.")
w("")
w("---")
w("")
w("## 5. ⚠ NEXT STEPS — THIS SECTION IS JUDGEMENT, NOT MEASUREMENT")
w("")
w("⭐ **G156 is the largest open row, and the table above shows why:** most clips read *not yet* "
  "in the \"feeds a signal\" column. G152 widened them; only the CMBS clip and the Indianapolis "
  "land bank have been turned into signals.")
w("")
w("1. ⭐ **`in_si_up_ibtr_appeals` first.** 10,071 rows, and **100% carry `stateParcelNumber`, "
  "`locationAddress` AND `petitionerName`** — a direct parcel key and an **owner name**, which is "
  "the thing G70, G71, G104, G90(b) and G147 are all blocked on. It also carries `attachments`, "
  "which are per-record documents for G153's provenance links.")
w("2. **`in_si_up_indy_rezoning`** — 13,414 cases, **100% with geometry**, 9,670 with a petitioner "
  "name. ⚠ Dates run 1990–2008, so AGE is the open question, not availability.")
w("3. **`in_si_up_brownfield`** — EPA has already computed `ssdist`, `ssvoltage`, `transdist`, "
  "`tlkv` and `raildist` for 1,483 Indiana sites. Not a new signal: a cross-check on our own G29 "
  "distances, and possibly better ones.")
w("4. **`in_si_up_indy_taxsale`** — 62,368 Marion parcels with `deltaxpen`, `delsatax` and "
  "`minimumbid`: the DOLLAR SIZE of a delinquency that D1/D4 currently carry only as a flag.")
w("")
w("⛔ **ASSESS BEFORE BUILDING.** Each needs its own D-code, an admission rule and a written "
  "\"so what\" — and a source that cannot earn one is a refusal to record, not a signal to ship. "
  "That is the governing principle applied as a veto, which is how it is meant to be used.")
w("")
w("⚠ **AND TWO THINGS THAT ARE NOT NEXT STEPS, because they were measured and closed:**")
w("- **WARN cannot be improved by scraping.** The address exists only inside the filing PDF, and "
  "most Indiana notices have no PDF. The 363-column multi-state `warn_notices` union has **every "
  "address column NULL on all 1,220 Indiana rows**.")
w("- **Owner name and assessed value are not hiding in the SI corpus.** "
  "`energy.si_d5_vacancy_derived` carries `parcel_owner`, `assessed_value`, `land_use`, `zoning` "
  "and `year_built` columns that are **100% NULL on all 967,366 Indiana rows**. The DLGF Gateway "
  "purchase is the only route.")
w("")

io.open(OUT, "w", encoding="utf-8").write("\n".join(L) + "\n")
print(f"\n  docs/SI_SIGNALS.md written ({len(L)} lines)")
print(f"  {len(cov)} distress signals · {len(intent)} declared-intent · {len(clips)} full-width clips")
print("\nDONE")
