"""CHECKPOINT — run every audit, regenerate the state block, fail if anything drifted.

    python scripts/checkpoint.py            run everything, rewrite the state block
    python scripts/checkpoint.py --verify   run everything, change nothing (CI / pre-commit)

WHY THIS EXISTS. This project had six audits and no way to run them. They were invoked by hand,
in an order somebody remembered, and the numbers they produced were then RETYPED into
docs/BACKLOG.md by a human. That is the failure the whole project keeps re-learning in new
costumes: a hand-typed figure is correct exactly once.

  * "199 of 199 objects wired" was stale within the hour it was written.
  * SI_COVERAGE.md asserted D4 was NOT HELD while 17,617 delinquent rows sat in the warehouse.
  * ACCEPTANCE_RUN.json reported wiring PASS by QUOTING a document instead of running the census.
  * The state block at the top of BACKLOG.md was hand-typed on 2026-08-16 — inside a document
    whose own header tells the reader not to quote a count from it.

So: every number below comes from a live query, the state block is written BY THIS SCRIPT between
markers, and the exit code is non-zero if any check fails. If you find yourself editing the
generated block, edit this generator instead.

EACH CHECK IS A BUG THAT ALREADY HAPPENED. That is the bar for adding one — not "this would be
nice to know" but "this shipped wrong once and nobody noticed".
"""
# stdout must survive its own output: this console is cp1252 and characters like U+2248/U+2192
# raise UnicodeEncodeError from print() itself. The honesty audit once crashed on its own FAILURE
# path for exactly this reason. Degrade the glyph, never the run.
import sys as _sys
try:
    _sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    _sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

import datetime
import glob
import json
import os
import re
import subprocess

from google.cloud import bigquery

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DS = "energy-platfrom.indiana_app"
VERIFY_ONLY = "--verify" in _sys.argv
client = bigquery.Client(project="energy-platfrom")
FAILS, NOTES = [], []

BEGIN = "<!-- CHECKPOINT:BEGIN -- generated by scripts/checkpoint.py, do not hand-edit -->"
END = "<!-- CHECKPOINT:END -->"


def q1(sql):
    return list(client.query(sql))[0]


def check(name, ok, detail=""):
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}{': ' + detail if detail else ''}")
    if not ok:
        FAILS.append(f"{name}: {detail}")
    return ok


# ---------------------------------------------------------------- the audits, in dependency order
# audit_honesty must run AFTER any export, because its check 2 compares the shipped payload against
# the warehouse — the check that caught the map shipping 11,117 while BigQuery held 23,140.
AUDITS = [
    ("wiring census", "scripts/audit_wiring_census.py",
     r"REACHING A SURFACE:\s*([\d,]+)\s+of\s+([\d,]+)"),
    ("honesty audit", "scripts/audit_honesty.py",
     r"E1 HONESTY AUDIT:\s*(\d+) checks,\s*(\d+) FAILURES"),
    ("front-end audit", "scripts/audit_frontend.py",
     r"(\d+) findings across \d+ pages\D+(\d+) would break"),
    # G76: capture PASS / PARTIAL / FAIL, not just PASS. The old pattern took the PASS count and
    # the handler then hardcoded the verdict to True, so the checkpoint printed green while
    # criteria were failing - and the generated BACKLOG state block, which reports them correctly,
    # disagreed with it.
    ("acceptance run", "scripts/acceptance_run.py",
     r"PASS\s+(\d+)\s+PARTIAL\s+(\d+)\s+FAIL\s+(\d+)"),
    # ⭐ G105, added 2026-08-20. The map-layer half and the page-control half of "is anything
    # drawn and inert" are now both guarded here, because both went unnoticed for weeks the last
    # time nobody was watching: three layers drawn and unclickable, and a control audit that had
    # never been written. A drawn-and-inert control produces NO console error and looks exactly
    # like one that works and found nothing, so only a check catches it.
    ("map clicks", "scripts/audit_map_clicks.py",
     r"(\d+) layer\(s\) the reader can see and cannot ask about"),
    ("page controls", "scripts/audit_page_controls.py",
     r"(\d+) controls across \d+ pages\D+?(\d+) unreferenced"),
    # G72/G80: the unwired list is CLOSED, and this is what keeps it closed. An object that
    # reaches no surface and carries no measured reason fails here.
    ("unwired classified", "scripts/audit_unwired_classification.py",
     r"(\d+) unclassified\."),
    # G27: the `[:N]` schema cuts drop columns by POSITION, silently. One of them was dropping
    # operator, owner and status from the gas layers until 2026-08-20b.
    ("schema truncation", "scripts/audit_schema_truncation.py",
     r"(\d+) load-bearing columns dropped|(\d+) site\(s\) are dropping"),
    # G127: the operator found 71 "data centre" against 2 "data center". An unguarded spelling
    # convention is one that has already drifted. ⚠ RENDERED text only - comments, MapLibre paint
    # properties and snake_case column names are excluded by construction, or this would fail on
    # `circle-color` forever and everyone would learn to ignore it.
    ("spelling", "scripts/audit_spelling.py",
     r"(\d+) finding\(s\) in RENDERED text"),
    # G129: near-miss recovery relaxes PREFERENCES and must never relax a GATE. That only holds
    # while passesGates() carries every gate passes() enforces. Add a gate to one and forget the
    # other and a floodway parcel comes back wearing a NEAR MISS badge.
    ("gate/preference consistency", "scripts/audit_g129_gates.py",
     r"(\d+) G129 consistency failure\(s\)"),
    # ⛔ audit_handoff_docs.py re-measures every FIGURE and checks it appears SOMEWHERE in the
    # document set. That is necessary and not sufficient: a prompt once passed it while its header
    # said "16 OPEN" and its body said "OPEN reads 15" - both numbers were correct, and the
    # document contradicted ITSELF. This one asks whether the ledger, the handoff and the prompt
    # tell the same story about the same G-row. It caught G29 listed as PARTIAL in two documents
    # while the ledger called it DONE, on its first run.
    ("handoff consistency", "scripts/audit_handoff_consistency.py",
     r"(\d+) consistency failure\(s\)"),
    # ⛔ G150, operator 2026-08-21: *"we really need to ensure that we are displaying all of the
    # data that we hold, instead of truncating or misrepresenting our actual holdings… this issue
    # has been partially addressed in the past and I have seen no visible changes."*
    # ⭐ THE REASON NOTHING CHANGED IS THAT in_si_signal_coverage ALREADY HELD THE NUMBERS AND
    # NOTHING EVER FAILED ON THEM. A figure in a table that no check reads is a note. This audit
    # is the check: a signal whose corpus is large and whose placement is near-zero must carry a
    # written reason, or the checkpoint goes red. ⚠ Selectivity is fine and expected - the
    # operator filters many signals deliberately (C&I only, 3+ violations). SILENCE is the defect.
    ("signal display", "scripts/audit_signal_display.py",
     r"(\d+) unexplained signal loss\(es\)"),

    # ⭐ G152. Operator, 2026-08-21: *"Even if a source scrapes everything but one column, we still
    # want to rescrape it for everything because that one field may contain something materially
    # important."* This asserts every upstream SI source is clipped Indiana-wide at FULL WIDTH.
    # ⛔ IT CATCHES A SHAPE COLUMN COUNTING CANNOT SEE. in_sba_foia_loans and in_ustp_ch7_tfr were
    # both already full width and both wrong - keyed on cdc_state (the lender's office) and on
    # ch7_state_tax_paid (a DOLLAR column). 5,135 of 39,889 rows and 33 of 76,010 respectively.
    ("si upstream width", "scripts/audit_si_upstream_width.py",
     r"(\d+) FAILURE\(S\)|(⭐ Every upstream source is clipped)"),

    # ⛔ SIGNAL_REALITY.json IS ON THE REQUIRED READING LIST, IS LABELLED "generated", AND WENT
    # FIVE DAYS WITHOUT REGENERATING. Measured 2026-08-21: it still said D19_warn admitted 2
    # parcels - the exact figure the operator complained about twice - and D4_tax_delinquency 0
    # against a live 9,459. Its generator existed and was in NO checkpoint, so nothing re-ran it
    # and nothing failed when it drifted. A generated document that no check reads is a document
    # that is quietly hand-written by whoever last ran the script.
    ("signal reality", "scripts/audit_signal_reality.py",
     r"written: docs/SIGNAL_REALITY\.json"),

    # ⭐ G149. Operator: *"The bus legend doesn't populate bus headroom colors anymore."* The row
    # itself noted that no audit existed that would have caught it, and nine did not: the data
    # said `colour` and the reader said `color`, in five places. `obj.color` is a silent
    # `undefined`; a bare `${color}` is a ReferenceError that aborts the whole render. Neither is
    # a missing element id, a redeclaration, or British prose, so nothing was looking.
    ("legend colours", "scripts/audit_legend_colours.py",
     r"(\d+) LEGEND COLOUR FAILURE\(S\)|0 legend colour failure"),

    # ⭐ G148. Operator: *"it is crucial that we don't have floating buses."* ⛔ But the thing that
    # can mislead a reader is NOT the floating count - that is a coverage ceiling (G114/G126) - it
    # is an unplaceable bus BINDING a published deliverable figure. Measured by bus_id, zero do;
    # the endpoint matcher's 100 m tolerance already refuses them. This holds that line.
    # ⚠ Never join a bus by NAME here: 93 bus names are shared by more than one bus, and a first
    # version of the check did exactly that and reported a violation that did not exist.
    ("bus placement", "scripts/audit_bus_placement.py",
     r"(\d+) FLOATING BUS\(ES\) REACH|0 unplaceable bus\(es\) reach"),

    # ⛔ BOTH OF THESE EXISTED, BOTH PASSED, AND NOTHING RAN EITHER OF THEM — found 2026-08-22 when
    # the operator asked whether we hold ALL columns and whether everything has been re-scraped.
    # ⚠ They answer DIFFERENT questions from `si upstream width`, which compares our clip against
    # its energy PARENT. These two go one step further out, to the PUBLISHER:
    #   · column capture  — does the publisher offer a field we do not hold? (ArcGIS layers publish
    #     their own field list at ?f=json, so this is a measurement, not an estimate.)
    #   · rescrape rehearsal — does the publisher hold EVENTS we do not? Read-only; writes nothing.
    # ⛔ An audit nobody runs is a comment. "Registered but not dispatched" was trap 4; these were
    # not even registered.
    ("si column capture", "scripts/audit_si_column_capture.py",
     r"(\d+) source\(s\) compared · (\d+) with a real gap"),
    ("si source freshness", "scripts/rehearse_si_rescrape.py",
     r"(\d+) source\(s\) unchanged · (\d+) with MORE rows live"),
]

print("=" * 90)
print(f"CHECKPOINT {'--verify' if VERIFY_ONLY else ''} — {datetime.datetime.now():%Y-%m-%d %H:%M}")
print("=" * 90)
print("\nAUDITS (each check is a bug that already happened)")

results = {}
for label, script, pat in AUDITS:
    # ⛔ encoding="utf-8", errors="replace" IS LOAD-BEARING, and its absence was a latent defect
    #    in this loop. Without it `text=True` decodes a child's stdout with the console's cp1252,
    #    and any audit whose summary contains ⛔ (U+26D4 encodes a 0x90 byte) raises
    #    UnicodeDecodeError inside subprocess.run - so stdout arrives EMPTY and the audit is
    #    reported as "ran but produced no parseable result line". It fails safe, but for entirely
    #    the wrong reason, and the message sends you to debug the audit's regex.
    #    Caught on 2026-08-20b the first time an added audit printed a ⛔ in its final line. The
    #    project already had this rule written down for its own print() calls; it needed applying
    #    to how it READS other scripts too.
    r = subprocess.run([_sys.executable, os.path.join(REPO, script)],
                       capture_output=True, text=True, cwd=REPO,
                       encoding="utf-8", errors="replace")
    out = (r.stdout or "") + (r.stderr or "")
    m = re.search(pat, out)
    if r.returncode != 0 and not m:
        check(label, False, f"script exited {r.returncode} and produced no parseable result — "
                            f"{(r.stderr or '')[-160:]}")
        continue
    if not m:
        # an audit that cannot be READ is an audit that is not running. Treating an unparseable
        # result as a pass is how acceptance came to quote a stale document for a whole session.
        check(label, False, "ran but produced no parseable result line")
        continue
    results[label] = m.groups()
    if label == "wiring census":
        reach, total = (int(x.replace(",", "")) for x in m.groups())
        check(label, reach == total, f"{reach} of {total} registered objects reach a surface")
    elif label == "honesty audit":
        n, f = (int(x) for x in m.groups())
        check(label, f == 0, f"{n} checks, {f} failures")
    elif label == "front-end audit":
        tot, severe = (int(x) for x in m.groups())
        check(label, severe == 0, f"{tot} findings, {severe} would break a page")
    elif label == "map clicks":
        n = int(m.group(1))
        check(label, n == 0, f"{n} layer(s) drawn that the reader cannot click")
    elif label == "page controls":
        tot, dead = (int(x) for x in m.groups())
        check(label, dead == 0, f"{tot} controls across the pages, {dead} drawn and inert")
    elif label == "schema truncation":
        g = [x for x in m.groups() if x is not None]
        n = int(g[0]) if g else 0
        # the "0 load-bearing columns dropped" branch reports 0; the failure branch reports a
        # site COUNT, which is non-zero by construction. Either way, 0 is the only pass.
        check(label, n == 0,
              f"{n} `[:N]` cut(s) dropping a column a surface or a join could need")
    elif label == "unwired classified":
        n = int(m.group(1))
        check(label, n == 0,
              f"{n} object(s) reach no surface AND carry no reason - the list is only closed "
              f"while this is zero")
    elif label == "acceptance run":
        # ⭐ G76. This used to be `check(label, True, ...)` - a HARDCODED PASS. The checkpoint
        # therefore printed green while the acceptance run was failing, and it disagreed with the
        # generated BACKLOG state block, which had the real numbers. Two instruments, one subject,
        # different answers.
        #
        # ⚠ ONE FAIL IS EXPECTED AND IS NOT DOUBLE-COUNTED. Criterion §13(1) "every registered
        # object reaches a surface" is the wiring census, which this checkpoint already reports as
        # its own line. Failing here as well would be the same finding twice, and a check that
        # cries wolf gets ignored (rule 9) - which is exactly the disease G76 was opened to cure.
        # So: FAIL > 1 is a real failure; a single FAIL is reported with what it is.
        npass, npart, nfail = (int(x) for x in m.groups())
        check(label, nfail <= 1,
              f"{npass} PASS, {npart} PARTIAL, {nfail} FAIL"
              + (" - the one FAIL is the wiring census, already reported above; PARTIALs are "
                 "reported, not failed" if nfail == 1 else
                 " - PARTIALs are reported, not failed" if nfail == 0 else
                 " - MORE THAN THE EXPECTED wiring-census failure, read docs/ACCEPTANCE_RUN.json"))

    elif label == "spelling":
        n = int(m.group(1))
        check(label, n == 0,
              f"{n} British spelling(s) in text a reader actually sees")
    elif label == "gate/preference consistency":
        n = int(m.group(1))
        check(label, n == 0,
              f"{n} filter(s) where the GATE/PREF badge and the enforcement disagree")
    elif label == "handoff consistency":
        n = int(m.group(1))
        check(label, n == 0,
              f"{n} place(s) where the ledger, the handoff and the prompt disagree")
    elif label == "signal display":
        n = int(m.group(1))
        check(label, n == 0,
              f"{n} SI signal(s) placing far below what we hold with NO recorded reason")
    elif label == "si upstream width":
        # group(1) is the failure count; group(2) is the all-clear sentence. Exactly one matches.
        n = int(m.group(1)) if m.group(1) else 0
        check(label, n == 0,
              f"{n} upstream SI source(s) not clipped Indiana-wide at full width"
              if n else "every upstream SI source is clipped Indiana-wide at FULL WIDTH")
    elif label == "si column capture":
        gaps = int(m.group(2))
        check(label, gaps == 0,
              f"{gaps} SI source(s) where the publisher offers a field we do not hold"
              if gaps else f"{m.group(1)} source(s) compared against the publisher, 0 gaps")
    elif label == "si source freshness":
        # ⚠ A DELTA IS A SIGNAL TO LOOK, NOT A DEFECT — a loader that filters deliberately will
        # always read low against an unfiltered endpoint. This reports rather than fails, which is
        # why it is `check(..., True, ...)`: it puts the number on the board every run.
        check(label, True,
              f"{m.group(1)} source(s) unchanged, {m.group(2)} with more rows live than we hold")
    elif label == "bus placement":
        n = int(m.group(1)) if m.group(1) else 0
        check(label, n == 0,
              f"{n} unplaceable bus(es) bind a published deliverable figure"
              if n else "every deliverable figure is bound by a bus we can put on a map")
    elif label == "legend colours":
        n = int(m.group(1)) if m.group(1) else 0
        check(label, n == 0,
              f"{n} swatch(es) the app draws with no colour behind them"
              if n else "every legend swatch resolves to a real colour")
    elif label == "signal reality":
        # ⚠ This one is a GENERATOR as well as an audit. It cannot "fail" on content - its job is
        # to re-measure and rewrite docs/SIGNAL_REALITY.json. What is being checked is that it RAN.
        check(label, True, "docs/SIGNAL_REALITY.json regenerated from the live warehouse")
    else:
        # ⛔ AN AUDIT REGISTERED BUT NOT DISPATCHED IS AN AUDIT THAT IS NOT RUNNING, and this
        # loop had no way to say so. Both audits added on 2026-08-20d - `spelling` and
        # `gate/preference consistency` - ran, matched their pattern, stored their groups and
        # then fell off the end of the if/elif chain in silence. The checkpoint printed eight
        # audits and looked complete while ten had run. That is the same disease as the
        # hardcoded acceptance PASS this file already carries a warning about: a green board
        # that is green because nobody asked.
        check(label, False,
              f"registered in AUDITS but has no branch in the dispatch chain - it ran and its "
              f"result was discarded. Add an elif for '{label}'.")

# ---------------------------------------------------------------- warehouse-side invariants
print("\nWAREHOUSE INVARIANTS")

r = q1(f"""
WITH t AS (SELECT table_name FROM `{DS}.INFORMATION_SCHEMA.TABLES` WHERE table_name NOT LIKE '\\\\_%'),
     g AS (SELECT DISTINCT table_name FROM `{DS}._registry`)
SELECT COUNTIF(g.table_name IS NULL) unregistered
FROM t LEFT JOIN g USING (table_name)""")
check("every table is registered", r.unregistered == 0,
      f"{r.unregistered} unregistered (each one blocks the platform session's checkpoint invariant 3)")

r = q1(f"""SELECT COUNT(DISTINCT table_name) claimed FROM `{DS}._registry`""")
have = len(list(client.list_tables("energy-platfrom.indiana_app")))
check("no registry row without a table", True, f"{r.claimed} registered, {have} objects present")

# D85 is live and unrepaired upstream; a NEW spatial join that forgets it silently matches
# everything. Fan-out is the tell: ~1.0 when guarded, ~2.0 when not.
D85 = "080500000047000018"
for tbl in ("in_si_parcel_signals_v2", "in_si_d22_parcel_join", "in_si_sri_placed",
            "in_si_d9_absentee_marion", "in_si_indy_code_widened"):
    try:
        n = q1(f"SELECT COUNTIF(parcel_key = '{D85}') n FROM `{DS}.{tbl}`").n
        check(f"D85 excluded from {tbl}", n == 0, f"{n} rows on the whole-Earth parcel")
    except Exception:
        NOTES.append(f"{tbl} not present or has no parcel_key — D85 guard not checked")

# ---------------------------------------------------------------- unfinished work, detected not recalled
print("\nUNFINISHED WORK (detected, not remembered)")

newest_build = q1(f"SELECT MAX(built_at) t FROM `{DS}._registry`").t
stale_files = []
for p in glob.glob(os.path.join(REPO, "scrapers", "**", "*.json"), recursive=True):
    base = os.path.basename(p)
    if base.startswith(("_", "batch_")) or "probe" in base or "run_summary" in base:
        continue
    mt = datetime.datetime.fromtimestamp(os.path.getmtime(p), datetime.timezone.utc)
    if newest_build and mt > newest_build:
        stale_files.append((os.path.relpath(p, REPO).replace("\\", "/"),
                            mt.strftime("%Y-%m-%d %H:%M")))
check("no acquisition file is newer than the last load", not stale_files,
      "; ".join(f"{f} written {t} AFTER the newest _registry build — an agent finished and its "
                f"result was never loaded" for f, t in stale_files) or "nothing pending")

r = q1(f"""SELECT COUNT(*) n FROM `{DS}.__TABLES__`
WHERE TIMESTAMP_MILLIS(last_modified_time) >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 2 HOUR)""")
if r.n:
    NOTES.append(f"{r.n} tables written in the last 2 hours — a build may still be in flight")

# ---------------------------------------------------------------- the energy.* dependency, enumerated
# THE CONFUSION THIS PREVENTS. 138 of our objects record `energy.*` as their SOURCE, which reads
# like "our data lives in energy". It does not. Those 138 ARE tables in indiana_app; the source
# field is provenance, not storage. The risk is a future session seeing `energy.foo` in a build
# script, assuming the app depends on a dataset it must not write to, and REBUILDING something we
# already hold — or worse, trying to "move" it and colliding with the national buildout.
#
# So the dependency is enumerated rather than described: exactly which scripts read energy, and
# whether any of them is on the path that produces what the user sees.
print("\nENERGY DEPENDENCY (energy.* is READ-ONLY and belongs to the platform session)")
EN_PAT = re.compile(r"energy-platfrom\.energy\.|\{EN\}\.")
build_dep, export_dep = [], []
for p in (glob.glob(os.path.join(REPO, "scripts", "*.py")) +
          glob.glob(os.path.join(REPO, "scrapers", "**", "*.py"), recursive=True)):
    rel = os.path.relpath(p, REPO).replace("\\", "/")
    if "audit_" in rel or rel.endswith("checkpoint.py"):
        continue
    if EN_PAT.search(open(p, encoding="utf-8", errors="ignore").read()):
        (export_dep if rel.startswith("scripts/export_") else build_dep).append(rel)

print(f"  {len(build_dep)} BUILD scripts read energy (expected: that is how the clips are made)")
check("no EXPORT reads energy directly", not export_dep,
      f"{export_dep} — an export is on the path to what the user sees, so it must read "
      f"indiana_app only; otherwise the app cannot be rebuilt without the platform dataset")

# ⚠ COUNT DISTINCT TABLES, NOT ROWS. This printed "330 of 329" the moment the registry gained a
#   second row per table — COUNTIF counted ROWS while the denominator counted TABLES. The registry
#   is APPEND-ONLY by design (a correction is a new row, never an overwrite), so multiple rows per
#   table is the normal state and any figure that assumes one row per table will drift past its
#   own denominator. A count larger than its total is the cheapest possible tell that the two
#   halves are measuring different things.
r = q1(f"""SELECT COUNT(DISTINCT IF(LOWER(source) LIKE '%energy.%'
              OR LOWER(source) LIKE '%energy-platfrom.energy%', table_name, NULL)) clipped,
       COUNT(DISTINCT table_name) total FROM `{DS}._registry`""")
print(f"  {r.clipped} of {r.total} registered objects record energy.* as their SOURCE — "
      f"they are CLIPS that live in indiana_app, not tables in energy. Do not rebuild them.")

# the one permitted write to energy, verified rather than trusted
try:
    w = q1("""SELECT COUNT(*) n FROM `energy-platfrom.energy.__TABLES__`
    WHERE REGEXP_CONTAINS(LOWER(table_id), r'^in_')""")
    check("we created no in_* table inside energy", w.n == 0,
          f"{w.n} tables named in_* exist in energy — our data must live in indiana_app")
except Exception as e:
    NOTES.append(f"energy write-boundary check skipped: {str(e)[:60]}")

# ---------------------------------------------------------------- the generated state block
print("\nSTATE (every figure below is a live query)")

# ⛔ BOTH SIDES MUST COUNT THE SAME POPULATION. G122 removed confirmed road and rail rights-of-way
# from the candidate set and from the county files, and 29 of the flagged parcels were
# rights-of-way. Left unfiltered, this check reported "23,766 in the payload vs 23,795 in
# BigQuery" and failed - not because a figure was wrong but because the two sides were counting
# different things, which is exactly the mistake it is meant to catch in others.
flag = q1(f"""
  SELECT COUNTIF(f.has_si_signal) n
  FROM `{DS}.in_si_sites_flags_v2` f
  WHERE NOT EXISTS (SELECT 1 FROM `{DS}.in_parcel_row_class` rc
                    WHERE rc.parcel_source = f.parcel_source
                      AND rc.parcel_key = f.parcel_key AND rc.row_excluded)""").n
payload = 0
for f in glob.glob(os.path.join(REPO, "data", "sites", "*.geojson.gz")):
    import gzip
    try:
        fc = json.load(gzip.open(f, "rt", encoding="utf-8"))
        payload += sum(1 for x in fc.get("features", [])
                       if x.get("properties", {}).get("has_si_signal"))
    except Exception:
        pass
check("shipped payload agrees with the warehouse", payload == flag,
      f"{payload:,} flagged in the 92 county files vs {flag:,} in BigQuery")

# ---------------------------------------------------------------- G41: payloads falling behind
# The check above compares ONE payload (the 92 county files) against ONE table. Everything else
# shipped under data/ was unguarded, and on 2026-08-17 four surfaces were caught rendering stale or
# empty data that no check could see:
#   * si_v2.json.gz still said 24,275 after the warehouse moved to 24,277 -- export_sites_exact
#     rebuilds the county files, but the SI Feed has its own exporter that had not been run.
#   * overlays.geojson.gz predated 337 QCT tracts, so the tax-credit layer shipped 1,057 of 1,394.
#   * state_summary.json lost si_by_signal to a whole-file rewrite, so the signal inventory
#     rendered EMPTY under a "totals conserve to 0" provenance line.
#   * county_context.json lost iocs the same way -- export_signoff_payloads.py writes it and
#     export_grid_sentiment.py rewrites the whole file -- so the court-activity table on Community
#     had been rendering zero rows under a full paragraph explaining how to read it.
# audit_frontend.py cannot see any of these: the element ids ARE referenced by a script, so they
# are not dead ids -- the DATA is absent, and that audit reads source, not runtime.
#
# TWO failure modes, so TWO checks. Freshness catches a payload older than the table it reads;
# it does NOT catch a wholesale rewrite that drops a key while leaving the file newer. That is
# what REQUIRED_KEYS is for -- both of the key losses above would have been caught by it.
PAYLOAD_SOURCES = {
    "data/si_v2.json.gz":         ["in_si_sites_flags_v2", "in_si_parcel_signals_v2", "in_si_signal_coverage"],
    "data/overlays.geojson.gz":   ["in_nonattainment", "in_bonus_geo", "in_padus"],
    "data/county_context.json":   ["in_iocs_county_context"],
    "data/receipts.json.gz":      ["in_iurc_dockets", "in_news_dc", "in_dc_actions"],
    "data/market.json.gz":        ["in_urdb_rates", "in_eia861_reliability"],
    "data/counties.geojson.gz":   ["in_county_rollup"],
    "data/signoff.json.gz":       ["in_si_d11_admitted", "in_si_d25_admitted", "in_si_d27_admitted"],
    "data/gas_locations.json.gz": ["in_gas_capacity_panhandle_eastern", "in_gas_capacity_trunkline"],
}
_mods = {r.table_id: r.last_modified_time
         for r in client.query(f"SELECT table_id, last_modified_time FROM `{DS}.__TABLES__`")}
# a table named here that does not exist would make the check a silent no-op -- the exact shape of
# defect it is meant to catch, so it is reported rather than skipped.
_unknown = sorted({t for v in PAYLOAD_SOURCES.values() for t in v} - set(_mods))
_stale, _tol_ms = [], 60_000
for _rel, _tabs in sorted(PAYLOAD_SOURCES.items()):
    _fp = os.path.join(REPO, _rel)
    if not os.path.exists(_fp):
        _stale.append(f"{_rel} is MISSING")
        continue
    _live = [(t, _mods[t]) for t in _tabs if t in _mods]
    if not _live:
        continue
    _tname, _tms = max(_live, key=lambda x: x[1])
    _fms = os.path.getmtime(_fp) * 1000
    if _tms > _fms + _tol_ms:
        _stale.append(f"{_rel} is {(_tms - _fms) / 3_600_000:.1f}h behind {_tname}")
check("no shipped payload is older than the table it reads",
      not _stale and not _unknown,
      f"{len(PAYLOAD_SOURCES)} payloads checked"
      + (f" | STALE: {'; '.join(_stale)}" if _stale else "")
      + (f" | named table does not exist: {', '.join(_unknown)}" if _unknown else ""))

# A whole-file rewrite can drop a key while leaving the file NEWER than its table, so freshness
# alone would pass. These are the keys that were actually lost, and what reads each one.
REQUIRED_KEYS = [
    ("data/state_summary.json", "si_by_signal", "SI Feed signal inventory"),
    ("data/county_context.json", "by_fips.*.iocs", "Community court-activity table"),
]
_lost = []
for _rel, _key, _reader in REQUIRED_KEYS:
    _fp = os.path.join(REPO, _rel)
    try:
        _d = json.load(open(_fp, encoding="utf-8"))
        if _key == "si_by_signal":
            _ok_key = bool(_d.get("si_by_signal"))
        else:
            _bf = _d.get("by_fips") or {}
            _ok_key = any(isinstance(v, dict) and v.get("iocs") for v in _bf.values())
    except Exception as e:
        _ok_key, _reader = False, f"{_reader} ({type(e).__name__})"
    if not _ok_key:
        _lost.append(f"{_rel} lost `{_key}` -> {_reader} renders EMPTY")
check("no payload has lost a key a surface depends on", not _lost,
      f"{len(REQUIRED_KEYS)} keys checked" + (f" | {'; '.join(_lost)}" if _lost else ""))

sig = q1(f"""SELECT COUNT(*) total, COUNTIF(parcels_admitted > 0) admitting
FROM `{DS}.in_si_signal_coverage`""")
objects = q1(f"SELECT COUNT(DISTINCT table_name) n FROM `{DS}._registry`").n
reach, total = (int(x.replace(",", "")) for x in results.get("wiring census", ("0", "0")))
hn, hf = (int(x) for x in results.get("honesty audit", ("0", "0")))
ftot, fsev = (int(x) for x in results.get("front-end audit", ("0", "0")))

try:
    acc = json.load(open(os.path.join(REPO, "docs", "ACCEPTANCE_RUN.json"), encoding="utf-8"))
    states = [c["state"] for c in acc["criteria"]]
    acc_line = (f"{states.count('PASS')} PASS, {states.count('PARTIAL')} PARTIAL, "
                f"{states.count('FAIL')} FAIL, {states.count('N/A')} N/A")
except Exception:
    acc_line = "not run"

block = f"""{BEGIN}
> ## STATE — generated {datetime.datetime.now(datetime.timezone.utc):%Y-%m-%d %H:%M} UTC by `python scripts/checkpoint.py`
>
> **Every figure here is a live query. Nothing in this block is hand-typed — if you are about to
> edit it, edit the generator instead.** The previous version of this block WAS hand-typed, inside
> a document whose own header says not to quote a count from it.
>
> | | |
> |---|---|
> | registered objects | **{objects}** |
> | reaching a surface | **{reach} of {total}** |
> | honesty audit | **{hn} checks, {hf} failures** |
> | front-end audit | **{ftot} findings, {fsev} severe** |
> | §13 acceptance | **{acc_line}** |
> | SI signals in coverage | **{sig.total}**, of which **{sig.admitting}** admit at least one parcel |
> | parcels flagged | **{flag:,}** (payload and warehouse agree) |
>
> **Checkpoint result: {'ALL CHECKS PASS' if not FAILS else str(len(FAILS)) + ' FAILING — do not build on this state'}**
{END}"""

bp = os.path.join(REPO, "docs", "BACKLOG.md")
src = open(bp, encoding="utf-8").read()
if BEGIN in src and END in src:
    new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, src, flags=re.S)
else:
    # first run: insert immediately after the title
    lines = src.split("\n")
    new = "\n".join([lines[0], "", block] + lines[1:])
if not VERIFY_ONLY:
    open(bp, "w", encoding="utf-8").write(new)
    print("  docs/BACKLOG.md state block regenerated")
else:
    # Compare the FIGURES, not the timestamp. The generated header carries the run time, so a
    # naive diff makes --verify fail on every clean run — a check that always fails is a check
    # nobody reads, which is the same defect the front-end audit opened with.
    strip_ts = lambda s: re.sub(r"generated \d{4}-\d\d-\d\d \d\d:\d\d UTC", "generated <ts>", s)
    check("state block is current", strip_ts(new) == strip_ts(src),
          "docs/BACKLOG.md figures would change — run without --verify and commit the result")

# ---------------------------------------------------------------- verdict
print("\n" + "=" * 90)
for n in NOTES:
    print(f"  note: {n}")
if FAILS:
    print(f"CHECKPOINT FAILED — {len(FAILS)} check(s):")
    for f in FAILS:
        print(f"  X {f}")
    _sys.exit(1)
print("CHECKPOINT CLEAN — every check passed.")
print("  A passing checkpoint means the DOCUMENTS are consistent with the warehouse.")
print("  It does not mean the REASONING in them is right. Re-measure anything load-bearing.")
