"""G123: move the "why" prose off the working surfaces and onto Insights.

Operator, 2026-08-20c: *"We need to cut out all of the 'Why' statements, since I was told that
there was too much text. Everything should be field + associated number (especially on the popup,
throughout the tables, and in the screener - we need to assume that the user is an energy
professional that understands these terms, but we should keep the insights tab as something that
people can refer to for additional help in understanding what we have)."*

⚠ THIS PARTIALLY REVERSES G21 AND THE GOVERNING PRINCIPLE, DELIBERATELY, AND THAT HAS TO BE SAID
PLAINLY RATHER THAN QUIETLY DONE. Three sessions were spent making every surface answer *so
what?*, and dozens of these blocks exist because of it. The operator is not withdrawing the
principle - they are RELOCATING it. The reader is an energy professional; the insight belongs on
the Insights page, not beside every number. So this MOVES the prose, it does not delete it, and
each block arrives on insights.html labelled with the page and section it came from.

⛔ WHAT MUST SURVIVE THE CUT, BECAUSE IT IS DISCLOSURE AND NOT EXPLANATION:
      the cap line             "showing the first 500 of 27,415"
      the three-state wording  "not measured here" vs "none"
      the vendor-licence badge on MISO figures
      the 2020 structures vintage
      the estimate-vs-published flag on a coordinate
Those are the difference between a number and a claim. Deleting them would make the tool
confident rather than concise, which is the opposite of the ask. A block matching any of them
STAYS WHERE IT IS and is reported as kept, so the decision is visible rather than silent.

⚠ audit_frontend.py CANNOT catch an over-deletion - removing a whole panel leaves no dangling
reference to find. So this script reports precisely what it moved, and the front-end audit,
page-controls audit and a browser check all run afterwards.

RE-SCRAPE COMMAND: python scripts/relocate_prose_to_insights.py [--check]
⚠ IDEMPOTENT: replace_safe on the SOURCE pages (a second run finds no .sowhat left to move), but
  ⛔ NOT on insights.html, which is APPENDED to. The appended region is delimited by a marker
  comment and is rewritten whole on each run, which is what makes re-running safe.
"""
import io
import os
import re
import sys

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHECK = "--check" in sys.argv

PAGES = ["index.html", "screener.html", "si.html", "community.html",
         "market.html", "grid.html", "data.html"]
INSIGHTS = "insights.html"
MARK_A = "<!-- G123:RELOCATED:BEGIN - generated by scripts/relocate_prose_to_insights.py -->"
MARK_B = "<!-- G123:RELOCATED:END -->"

OPEN_RE = re.compile(r"<div\b[^>]*class=\"[^\"]*\bsowhat\b[^\"]*\"[^>]*>", re.I)
DIV_RE = re.compile(r"<div\b[^>]*>|</div\s*>", re.I)
HEAD_RE = re.compile(r"<h[1-4]\b[^>]*>(.*?)</h[1-4]\s*>", re.S | re.I)
TAG_RE = re.compile(r"<[^>]+>")

# DISCLOSURE. A block matching any of these stays put.
KEEP = [
    (re.compile(r"showing\s+(?:the\s+)?first\s+[\d,{$]|showing\s+[\d,{$]+\s+of|capped\b", re.I),
     "cap line"),
    (re.compile(r"not measured|cannot assess|measured, not missing|left out of the denominator",
                re.I), "three-state wording"),
    (re.compile(r"orennia|licensed|licence|subscription|vendor", re.I), "vendor-licence badge"),
    (re.compile(r"newest indiana record|january 2020|2020-01|structures layer", re.I),
     "2020 structures vintage"),
    (re.compile(r"estimated positions|not published|estimate\b", re.I),
     "estimate-vs-published flag"),
]

MARKER_RE = re.compile(r"⚠|⛔|&#9888;|&#9940;")
assert OPEN_RE.search('<div class="sowhat">x</div>'), "OPEN_RE self-test"
assert MARKER_RE.search("&#9888; estimated"), "MARKER_RE must see the HTML entity form"
assert HEAD_RE.search("<h3>Title</h3>").group(1) == "Title", "HEAD_RE self-test"


def find_blocks(blob):
    """Return [(start, end, inner_html)] for every balanced <div class=sowhat> ... </div>."""
    out = []
    for m in OPEN_RE.finditer(blob):
        depth, i = 1, m.end()
        while depth and i < len(blob):
            t = DIV_RE.search(blob, i)
            if not t:
                break
            depth += 1 if t.group(0).lower().startswith("<div") else -1
            i = t.end()
        if depth == 0:
            out.append((m.start(), i, blob[m.end():i - len(re.search(r"</div\s*>$",
                        blob[:i], re.I).group(0))]))
    return out


def context_for(blob, pos):
    """The nearest heading above this block, so the reader knows where it came from."""
    best = None
    for h in HEAD_RE.finditer(blob, 0, pos):
        best = h
    if not best:
        return None
    return re.sub(r"\s+", " ", TAG_RE.sub("", best.group(1))).strip()[:80]


ID_RE = re.compile(r"\bid=\"([A-Za-z][\w-]*)\"")
assert ID_RE.findall('<span id="wd-answer">x</span>') == ["wd-answer"], "ID_RE self-test"

# Every id any script anywhere reaches for. Union across the pages and app.js/common.js, because
# a block on one page can be filled by a shared script.
referenced_ids = set()
for fn in PAGES + [INSIGHTS, "app.js", "common.js"]:
    fp = os.path.join(REPO, fn)
    if os.path.exists(fp):
        src = io.open(fp, encoding="utf-8").read()
        referenced_ids |= set(re.findall(r"getElementById\(\s*[\"']([\w-]+)[\"']", src))
        referenced_ids |= set(re.findall(r"\$\(\s*[\"']([\w-]+)[\"']\s*\)", src))
        referenced_ids |= set(re.findall(r"querySelector\(\s*[\"']#([\w-]+)[\"']", src))

moved, kept, splits, has_live, total_chars = [], [], [], [], 0
edits = {}

for page in PAGES:
    p = os.path.join(REPO, page)
    if not os.path.exists(p):
        continue
    blob = io.open(p, encoding="utf-8").read()
    blocks = find_blocks(blob)
    drop = []
    for start, end, inner in blocks:
        text = re.sub(r"\s+", " ", TAG_RE.sub(" ", inner)).strip()
        if not text:
            continue

        # ⛔ NEVER MOVE A BLOCK THAT CARRIES A LIVE ELEMENT, AND THIS COST A ROUND TRIP.
        # The first run moved 63 blocks and broke SIX PAGES - 18 findings, every one fatal. These
        # .sowhat divs are not pure prose: they wrap `<span id="wd-answer">`, `<span id="inv-n">`
        # and fourteen more placeholders that the page's own script fills with the COMPUTED VALUE.
        # Removing the div removed the id, `getElementById` returned null, and the next property
        # write threw and killed the rest of the script - the exact "two safe changes are fatal
        # together" failure this project already has on record from the L-frpp checkbox.
        # ⚠ The value is the thing G123 wants to KEEP; only the sentence around it should go. That
        # is a per-block restructure, not a sweep, so these are left for the G128 layout pass and
        # reported here rather than silently skipped.
        # ⚠ THE WHOLE BLOCK, NOT JUST ITS INNER HTML. The id is usually ON the div - the pages are
        # written as `<div class="sowhat" id="wd-answer">measuring…</div>`, a placeholder the
        # script replaces wholesale. Searching `inner` found the id in 1 block of 63 and missed
        # the other 17, so the guard reported almost nothing and the pages broke anyway.
        ids = ID_RE.findall(blob[start:end])
        live = [i for i in ids if i in referenced_ids]
        if live:
            has_live.append((page, ", ".join(live[:4]), text[:70]))
            continue

        why = next((lbl for rx, lbl in KEEP if rx.search(text)), None)
        if why:
            # ⚠ A BLOCK CAN BE BOTH, AND THE FIRST VERSION KEPT THE WHOLE THING. index.html's
            # queue note opens with pure explanation - "the queue is your competition for the same
            # study slots" - and then carries a real disclosure: "Candidate buses are ESTIMATED
            # positions ... treat them as about here, never as surveyed." Keeping all of it left
            # explanation on the page; moving all of it would have deleted a disclosure.
            # This codebase marks disclosure with ⚠ / ⛔ consistently, so the block is split there:
            # everything before the marker moves, the marker onward stays.
            m = MARKER_RE.search(inner)
            if m and m.start() > 40:
                head, tail = inner[:m.start()].strip(), inner[m.start():].strip()
                moved.append((page, context_for(blob, start), head))
                total_chars += len(TAG_RE.sub(" ", head))
                kept.append((page, why + " (block SPLIT; disclosure half kept)",
                             re.sub(r"\s+", " ", TAG_RE.sub(" ", tail)).strip()[:90]))
                splits.append((page, start, end, tail))
                continue
            kept.append((page, why, text[:90]))
            continue
        moved.append((page, context_for(blob, start), inner.strip()))
        total_chars += len(text)
        drop.append((start, end))
    page_splits = [(s, e, tail) for pg, s, e, tail in splits if pg == page]
    if drop or page_splits:
        # ⛔ ONE REVERSE-ORDERED PASS OVER BOTH KINDS OF EDIT. Applying the splits and then the
        # deletions in two passes was wrong: every offset indexes the ORIGINAL text, so a deletion
        # ABOVE a split that had already changed the string used a stale offset and would have cut
        # from the wrong place. Merged and sorted descending, each edit only ever moves text that
        # sits after it, so no offset is invalidated before it is used.
        ops = [(s, e, tail) for s, e, tail in page_splits] + [(s, e, None) for s, e in drop]
        new = blob
        for s, e, tail in sorted(ops, key=lambda x: -x[0]):
            if tail is not None:
                new = new[:s] + '<div class="sowhat">' + tail + "</div>" + new[e:]
                continue
            # take the surrounding whitespace with it so the markup does not gap
            a = s
            while a > 0 and new[a - 1] in " \t":
                a -= 1
            b = e
            while b < len(new) and new[b] in " \t":
                b += 1
            if b < len(new) and new[b] == "\n":
                b += 1
            new = new[:a] + new[b:]
        edits[page] = new

print("G123 - RELOCATE THE 'WHY' PROSE TO INSIGHTS")
print(f"  {'page':16} {'moved':>7} {'kept as disclosure':>20}")
for page in PAGES:
    m = sum(1 for x in moved if x[0] == page)
    k = sum(1 for x in kept if x[0] == page)
    print(f"  {page:16} {m:>7} {k:>20}")
print(f"  {'TOTAL':16} {len(moved):>7} {len(kept):>20}   ({total_chars:,} characters moved)")

if kept:
    print("\n  ⭐ LEFT IN PLACE because it is disclosure, not explanation:")
    for page, why, text in kept:
        print(f"    {page:16} [{why}] {text[:70]}…")

if has_live:
    print(f"\n  ⛔ {len(has_live)} BLOCK(S) NOT MOVED - each wraps a live element the page's own")
    print("     script writes into. Moving them broke six pages on the first run (18 fatal")
    print("     findings). The VALUE is what G123 wants to keep; only the sentence around it")
    print("     should go, and that is a per-block restructure for the G128 layout pass:")
    for page, ids, text in has_live:
        print(f"    {page:16} [{ids}] {text}…")

if CHECK:
    print("\n  --check: nothing written")
    sys.exit(0)

# ---- write the source pages ------------------------------------------------------------------
for page, new in edits.items():
    io.open(os.path.join(REPO, page), "w", encoding="utf-8", newline="").write(new)

# ---- rebuild the appended region on insights.html ---------------------------------------------
ip = os.path.join(REPO, INSIGHTS)
ins = io.open(ip, encoding="utf-8").read()

by_page = {}
for page, ctx, html in moved:
    by_page.setdefault(page, []).append((ctx, html))

TITLES = {"index.html": "Map console", "screener.html": "Site screener",
          "si.html": "Seller intent", "community.html": "Community &amp; posture",
          "market.html": "Market &amp; tariffs", "grid.html": "Grid", "data.html": "Data"}

parts = [MARK_A,
         '<section class="wrap" id="relocated">',
         '  <h2>Why each measure is on the page</h2>',
         '  <p class="hint">Moved here from the working surfaces on 2026-08-20d so those pages '
         'carry field and value only (G123). Nothing was deleted &mdash; every note below still '
         'says what its number changes about a decision, grouped by the page it belongs to.</p>']
for page in PAGES:
    if page not in by_page:
        continue
    parts.append(f'  <div class="card">')
    parts.append(f'    <h2>{TITLES.get(page, page)} '
                 f'<span class="hint">&mdash; {len(by_page[page])} notes</span></h2>')
    last_ctx = None
    for ctx, html in by_page[page]:
        if ctx and ctx != last_ctx:
            parts.append(f'    <h3 style="margin:14px 0 4px;font-size:13px;'
                         f'text-transform:uppercase;letter-spacing:.04em;opacity:.7">{ctx}</h3>')
            last_ctx = ctx
        parts.append(f'    <div class="sowhat">{html}</div>')
    parts.append("  </div>")
parts.append("</section>")
parts.append(MARK_B)
region = "\n".join(parts)

if MARK_A in ins and MARK_B in ins:
    a, b = ins.index(MARK_A), ins.index(MARK_B) + len(MARK_B)
    ins = ins[:a] + region + ins[b:]
else:
    # insert before the closing body so it lands inside the document, not after it
    m = re.search(r"</body\s*>", ins, re.I)
    at = m.start() if m else len(ins)
    ins = ins[:at] + region + "\n" + ins[at:]
io.open(ip, "w", encoding="utf-8", newline="").write(ins)

print(f"\n  {INSIGHTS}: relocated region rewritten "
      f"({len(by_page)} page sections, {len(moved)} notes)")
print("\n⚠ NEXT, and none of these is optional:")
print("   python scripts/stamp_assets.py")
print("   python scripts/audit_frontend.py")
print("   python scripts/audit_page_controls.py")
print("   then open every page - audit_frontend CANNOT see an over-deletion")
print("G123 RELOCATION COMPLETE")
